# 기계학습

### 담당교수 : 장원중

In [1]:
# 그래프 한글이 깨질때 & 마이너스 부호 사용

import sys, os
from matplotlib import font_manager, rc 
import matplotlib.pyplot as plt

# 한글 폰트 설정 : 윈도우 폰트를 사용하는 경우 
font_name = font_manager.FontProperties(fname="c:/Windows/Fonts/malgun.ttf").get_name()
rc('font', family=font_name) 

# 운영체제별 한글 폰트 설정
# if os.name == 'posix': # Mac 환경 폰트 설정
#     rc('font', family='AppleGothic')
# elif os.name == 'nt': # Windows 환경 폰트 설정
#     rc('font', family='Malgun Gothic')

plt.rc('axes', unicode_minus=False) # 마이너스 폰트 설정

# 유니코드에서 음수 부호설정
rc('axes', unicode_minus=False)

# 부모 디렉터리의 파일을 가져올 수 있도록 설정
sys.path.append(os.pardir)     

# jupyter에서 matplotlib 그래프를 출력 영역에 표시  
%matplotlib inline 

# 레티나 설정 - 폰트 주변이 흐릿하게 보이는 것을 방지해 글씨가 좀 더 선명하게 보임
%config InlineBackend.figure_format = 'retina'

In [2]:
# 운영체제별 이름 

import platform

platform.system()

'Windows'

In [3]:
# 파이썬 버전 확인

import sys
import platform

print("--sys.version—")
print(sys.version)

print("--python_version—")
print(platform.python_version())

--sys.version—
3.11.7 | packaged by Anaconda, Inc. | (main, Dec 15 2023, 18:05:47) [MSC v.1916 64 bit (AMD64)]
--python_version—
3.11.7


# 범주형 변수 변환

## 원핫인코딩(One-hot-encoding) with get_dummies, OneHotEncoder, ColumnTransformer

In [4]:
# 라이브러리 읽어오기 

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os 

In [28]:
# 데이터 읽어오기 
data = pd.read_csv(os.getcwd()+'/student90.csv')

# 데이터의 형상 
# - shape 속성 : 데이터의 (행, 열) 크기를 확인 
print(data.shape)   # (90, 4)
data[:10]           # 10행 출력 

(90, 4)


no sex  weight_kg  height_cm
0   1   m         98        198
1   2   m         77        170
2   3   m         70        170
3   4   m         90        198
4   5   m         71        170
5   6   m         70        165
6   7   m         73        193
7   8   m         59        142
8   9   m         68        137
9  10   m         86        155

In [30]:
# OneHotEncoder 클래스를 이용한 원핫인코딩 
# - OneHotEncoder 클래스는 모든 특성을 범주형이라고 가정하여 수치형 열을 포함한 모든 열에 인코딩을 수행함
# - sparse_output=False : transform을 이용하여 바로 변환 결과를 얻을 경우

from sklearn.preprocessing import OneHotEncoder 

# 준비 
ohe = OneHotEncoder(sparse_output=False)  

# 인코딩
data_ohe = ohe.fit_transform(data) 
feature_names = ohe.get_feature_names_out()  # feature names 추출 

print(data_ohe.shape)  # 형상 출력 
print(data_ohe[:1,:])  # 1행 출력  
print(feature_names)   # feature names 출력     

(90, 154)
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
['no_1' 'no_2' 'no_3' 'no_4' 'no_5' 'no_6' 'no_7' 'no_8' 'no_9' 'no_10'
 'no_11' 'no_12' 'no_13' 'no_14' 'no_15' 'no_16' 'no_17' 'no_18' 'no_19'
 'no_20' 'no_21' 'no_22' 'no_23' 'no_24' 'no_25' 'no_26' 'no_27' 'no_28'
 'no_29' 'no_30' 'no_31' 'no_32' 'no_35' 'no_36' 'no_37' 'no_38' 'no_39'
 'no_40' 'no_41' 'no_42' 'no_43' 'no_44' 'no_45' 'no_46' 'no_47' 'no_48'
 'no_49' 'no_50' 'no_51' 'no_52' 'no_53' 'no_54' 'no_55' 'no_56' 'no_57'
 'no_58' 'no_59' 'no_60' 'no_61' 'no_62' 'no_63' 'no_64' 'no_65' 'no_66'
 '

In [31]:
# ColumnTransformer 클래스를 이용한 원핫인코딩 
# - ColumnTransformer 클래스는 범주형 변수에는 원핫인코딩, 수치형 변수에는 스케일링을 적용함

from sklearn.compose import ColumnTransformer  
from sklearn.preprocessing import OneHotEncoder 
from sklearn.preprocessing import StandardScaler  

# 준비 
ct = ColumnTransformer([
    ('scaling', StandardScaler(), ['weight_kg',	'height_cm']),
    ('onehot', OneHotEncoder(sparse_output=False), ['sex'])
])

# 인코딩
data_ct = ct.fit_transform(data)
feature_names = ct.get_feature_names_out()  # feature names 추출 

print(data_ct.shape)   # 형상 출력 
print(data_ct[:1,:])   # 1행 출력  
print(feature_names)   # feature names 출력     

(90, 4)
[[1.99325723 1.75590438 0.         1.        ]]
['scaling__weight_kg' 'scaling__height_cm' 'onehot__sex_f' 'onehot__sex_m']


In [32]:
# 더미코딩 (Dummy coding) with get_dummies(drop_first=True)
# - 범주형 변수의 레벨이 n개 일때 해당 레벨 개수만큼 가변수를 만들면 다중공선성이 생기기 때문에 이를 방지하기 위해 n-1개의 가변수를 만드는 방법을 쓰는 것이 더미코딩

# 원핫인코딩 
dummies = pd.get_dummies(data)    
print(list(data.columns), data.shape)        # 원래 데이터 
print(list(dummies.columns), dummies.shape)  # 원핫인코딩된 데이터 
print(dummies[:5])                           # 원핫인코딩된 데이터 5행 출력 

print('-'*50)

# 더미코딩 
dummies2 = pd.get_dummies(data, drop_first=True)
print(list(dummies2.columns), dummies2.shape)  # 더미코딩된 데이터  
print(dummies2[:5])                            # 더미코딩된 데이터 5행 출력  

['no', 'sex', 'weight_kg', 'height_cm'] (90, 4)
['no', 'weight_kg', 'height_cm', 'sex_f', 'sex_m'] (90, 5)
   no  weight_kg  height_cm  sex_f  sex_m
0   1         98        198      0      1
1   2         77        170      0      1
2   3         70        170      0      1
3   4         90        198      0      1
4   5         71        170      0      1
--------------------------------------------------
['no', 'weight_kg', 'height_cm', 'sex_m'] (90, 4)
   no  weight_kg  height_cm  sex_m
0   1         98        198      1
1   2         77        170      1
2   3         70        170      1
3   4         90        198      1
4   5         71        170      1


# 레이블 인코딩(Label encoding) with LabelEncoder

In [37]:
std_card = pd.DataFrame({
    'grade': ['A', 'B', 'C', 'D'],
    'class': ['H', 'M', 'L', 'H']    
})

std_card

grade class
0     A     H
1     B     M
2     C     L
3     D     H

In [48]:
# grade 변수 레이블인코딩 

from sklearn.preprocessing import LabelEncoder 

le = LabelEncoder() 
grade_le = le.fit_transform(std_card['grade']) # 레이블인코딩 
print(grade_le)
print(le.classes_)                    # 변환된 label classes 확인 
print(le.inverse_transform(grade_le)) # 역변환  

[0 1 2 3]
['A' 'B' 'C' 'D']
['A' 'B' 'C' 'D']


In [49]:
# class 변수 레이블인코딩 

class_le = le.fit_transform(std_card['class']) # 레이블인코딩
print(class_le)
print(le.classes_)                    # 변환된 label classes 확인 
print(le.inverse_transform(class_le)) # 역변환  

[0 2 1 0]
['H' 'L' 'M']
['H' 'M' 'L' 'H']


In [50]:
# grade, class 두 개의 변수를 레이블인코딩 

from sklearn.preprocessing import LabelEncoder 

std_card_le = pd.DataFrame() 
for col in std_card.columns:
    le = LabelEncoder()
    std_card_le[col] = le.fit_transform(std_card[col])

In [51]:
std_card_le

grade  class
0      0      0
1      1      2
2      2      1
3      3      0

# 구간 분할(Binning) with cut, KBinsDiscretizer

In [65]:
# 판다스의 cut 함수 
# - bin 수 지정
# - 레이블 지정하지 않음  

from pandas import cut 

binned_weight = cut(data['weight_kg'], 5)  # bin수 지정 
binned_weight.value_counts()

(56.4, 69.8]      32
(69.8, 83.2]      29
(42.933, 56.4]    14
(83.2, 96.6]       9
(96.6, 110.0]      6
Name: weight_kg, dtype: int64

In [66]:
print(len(binned_weight))
print(binned_weight.head(5))

90
0    (96.6, 110.0]
1     (69.8, 83.2]
2     (69.8, 83.2]
3     (83.2, 96.6]
4     (69.8, 83.2]
Name: weight_kg, dtype: category
Categories (5, interval[float64, right]): [(42.933, 56.4] < (56.4, 69.8] < (69.8, 83.2] < (83.2, 96.6] < (96.6, 110.0]]


In [67]:
# 판다스의 cut 함수 
# - bin 수 지정  
# - 레이블 지정함  

from pandas import cut 

binned_weight = cut(data['weight_kg'], 5, labels=["A","B","C","D","E"])  # bin수 지정 
binned_weight.value_counts()

B    32
C    29
A    14
D     9
E     6
Name: weight_kg, dtype: int64

In [68]:
print(len(binned_weight))
print(binned_weight.head(5))

90
0    E
1    C
2    C
3    D
4    C
Name: weight_kg, dtype: category
Categories (5, object): ['A' < 'B' < 'C' < 'D' < 'E']


In [69]:
# 판다스의 cut 함수 
# - bin의 범위를 지정 
# - 레이블 지정하지 않음  

bin_edges = [0, 50, 60, 70, 80, 90, 100, float('inf')]
# 0초과~50이하, 50초과~60이하, ..., 100초과 

binned_weight2 = cut(data['weight_kg'], bin_edges)  
binned_weight2.value_counts()

(60.0, 70.0]     32
(50.0, 60.0]     19
(70.0, 80.0]     17
(80.0, 90.0]     12
(0.0, 50.0]       4
(90.0, 100.0]     3
(100.0, inf]      3
Name: weight_kg, dtype: int64

In [70]:
print(len(binned_weight2))
print(binned_weight2.head(5))

90
0    (90.0, 100.0]
1     (70.0, 80.0]
2     (60.0, 70.0]
3     (80.0, 90.0]
4     (70.0, 80.0]
Name: weight_kg, dtype: category
Categories (7, interval[float64, right]): [(0.0, 50.0] < (50.0, 60.0] < (60.0, 70.0] < (70.0, 80.0] < (80.0, 90.0] < (90.0, 100.0] < (100.0, inf]]


In [71]:
# 판다스의 cut 함수 
# - bin의 범위를 지정 
# - 레이블 지정함 

bin_edges = [0, 50, 60, 70, 80, 90, 100, float('inf')]
# 0초과~50이하, 50초과~60이하, ..., 100초과 

binned_weight2 = cut(data['weight_kg'], bin_edges, labels=[1,2,3,4,5,6,7])  
binned_weight2.value_counts()

3    32
2    19
4    17
5    12
1     4
6     3
7     3
Name: weight_kg, dtype: int64

In [72]:
print(len(binned_weight2))
print(binned_weight2.head(5))

90
0    6
1    4
2    3
3    5
4    4
Name: weight_kg, dtype: category
Categories (7, int64): [1 < 2 < 3 < 4 < 5 < 6 < 7]


In [78]:
# 사이킥런의 KBinsDiscretizer 함수 
# - KBinsDiscretizer 함수를 이용하면, 지정한 bins 수대로 데이터를 분할한 후 각 구간 별로 원핫인코딩을 적용할 수 있음

from sklearn.preprocessing import KBinsDiscretizer 

kb = KBinsDiscretizer(n_bins=5, strategy='uniform')
kb_weight = kb.fit_transform(np.array(data['weight_kg']).reshape(-1,1))
kb_weight = kb_weight.toarray()
print(kb_weight.shape)   # 형상 출력 
print(kb_weight[:5,:])   # 5행 출력 

(90, 5)
[[0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]]


In [76]:
data['weight_kg'].head(5)

0    98
1    77
2    70
3    90
4    71
Name: weight_kg, dtype: int64